channels:
  - conda-forge
dependencies:
  - cartopy
  - fsspec
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::geoviews
  - pyviz/label/dev::datashader
  - metpy
  - numpy
  - xarray
